### ISSUE TITLE
Duplicated `version` outout

### ISSUE THREAD

**Issue by lakscastro** [gonuit/rps#1]
For some reason on run it on windows as `rps --version` the output is duplicated:

![image](https://user-images.githubusercontent.com/51419598/153408820-50b6ffb4-a001-47b7-a988-ec03d96fb7e0.png)

**Environment**
```
Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "windows_x64"

Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (4 months ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

**Comment by gonuit** [comment]
Hi @lakscastro,
Unfortunately, I was not able to reproduce that 🤔.
If this problem persists, feel free to reopen this issue.
