### ISSUE TITLE
[Question] Is it possible to pass command as an argument?

### ISSUE THREAD

**Issue by g0dzillaa** [gonuit/rps#13]
I am aware that I can pass arguments as mentioned in the docs like:

```bash
rps gen
# you can also provide additional arguments
rps gen --verbose
```

However, I want a string to be passed (actually, an argument).

This is what I am trying to do: 

```
package: cd packages && very_good create flutter_package <name> && cd ..
```

Here I am not sure if it is possible to pass the <name> from rps like `rps package <name>`

**Comment by gonuit** [comment]
Hi @g0dzillaa, 
At the moment it is not possible, but you are not the first person to ask about it, so I think it is time to add this feature 😅... 

Will let you know soon about the progress.

**Comment by gonuit** [comment]
#### Hi @g0dzillaa,
You can test the `dev` version of the package ([0.8.0-dev.1](https://pub.dev/packages/rps/versions/0.8.0-dev.1)) with experimental support for positional arguments, yet this is not the final solution as I am still working on that and there might be some changes in the functionality. 

Let me know if that works for you. Currently, only basic support for positional arguments is added.
  
  
---
#### Usage example:
```dart
scripts:
  hello: echo "${1}" && echo "${0}:${1}"
```
```bash
$ rps hello James Bond
```
```
> hello
$ echo "Bond" && echo "James Bond"

Bond
James Bond
```

**Comment by christianmemije** [comment]
@gonuit I was JUST asking for this, so I am happy to hear you are beta-ing it. 💪🏾

**Comment by g0dzillaa** [comment]
Awesome! @gonuit 🎉 

Thank you for taking time to consider this request. Works great for me ❤️ 🚀
