### ISSUE TITLE
Reqeust: command to list scripts (derry is good example)

### ISSUE THREAD

**Issue by jibbers42** [gonuit/rps#15]
This project seems great and I'm looking at switching over from derry for the platform specific script support and see a feature that I'll miss.

My request is for a `list` or `ls` command to avoid consulting pubspec to remember script names. I think a tree type output similar to `derry ls` is a good example:
```
> derry ls
+ my_project@1.1.0+3
│
├── gen
├── gen:delete
├── outdated
└── prepare
```
As a small tag along to this request, a `-h` flag that shows help would be cool too :)

**Comment by gonuit** [comment]
### Hi @jibbers42!

Proposed changes are now live on 0.8.0! 😃

**Comment by jibbers42** [comment]
Great - I see the following on Windows Powershell, but not a big deal to me
Thanks for this!

![image](https://github.com/gonuit/rps/assets/797824/4776d5a4-3fbb-4cca-b312-fc3ed89bf109)

**Comment by neiljaywarner** [comment]
@jibbers42  How did you decide to use this over derry? I like derry but this seems better and/or better maintained? or at least more recent and better docs :)
