### ISSUE TITLE
introduce scripts.yaml file to store commands for easier reading.

### ISSUE THREAD

**Issue by masreplay** [gonuit/rps#23]
have more than 10 commands in pubspec.yaml makes it too long to read split it into a new file

<img width="782" alt="Screenshot 2024-09-21 at 9 49 56 AM" src="https://github.com/user-attachments/assets/cc78d992-18c0-4440-afee-50097d1eaac6">

**Comment by masreplay** [comment]
fork
https://github.com/masreplay/rps

**Comment by gonuit** [comment]
### Hi @masreplay 👋🏻 
Thank you for your contribution, it has now been merged. I will be working more on this package in the coming weeks, I will let you know when the new version of the package is available.

**Comment by masreplay** [comment]
Thanks

**Comment by gonuit** [comment]
### Hi @masreplay 👋🏻 

The above change is now available in [rps version 0.9.0](https://pub.dev/packages/rps/versions/0.9.0).

However, there are some minor changes to the implementation provided.
- `scripts.yaml` is renamed to `rps.yaml` － to reduce the risk of conflicts with other files.
- in the `rps.yaml` file, the `scripts` key should be specified, as in the `pubspec.yaml` file － this is to allow configuration properties to be inserted into this file in the future.

For more information, see the readme  － [external scripts file section.](https://pub.dev/packages/rps#-external-scripts-file)
