### ISSUE TITLE
Failed to load dynamic library

### ISSUE THREAD

**Issue by coodin** [gonuit/rps#7]
I have encountered an error but not sure related with your repo so this was  the error
** Invalid argument(s): Failed to load dynamic library 'C:\Users\legol\AppData\Local\Pub\Cache\hosted\pub.dev\rps-0.6.4\lib\native\rps.dll': error code 126
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      execute (package:rps/bindings/execute.dart:30:32)
<asynchronous suspension>
#3      RunCommand.run (package:rps/commands/run_command.dart:35:22)
<asynchronous suspension>
#4      main (file:///C:/Users/legol/AppData/Local/Pub/Cache/hosted/pub.dev/rps-0.6.4/bin/rps.dart:38:26)  
<asynchronous suspension>
** I searched stackoverflow to find a solution but I really didn't  grasp it to solve my problem because there was one of them that tried to communicate with c++ so it was not what I looking for.

**Comment by JuhaKarhusaari** [comment]
Same problem here.
Do anyone have solutions for this? 
I think for setting up these scripts it must be straight forward process without any random hacking. **Also** in Windows platform.

**Comment by JuhaKarhusaari** [comment]
I also encountered this issue today. 
Seems like `Visual Studio - develop for Windows` must be installed.  
So basic 'flutter doctor'-case :sweat_smile:.

**Comment by coodin** [comment]
I will check your suggestion thank you

**Comment by gonuit** [comment]
Interesting 🤔, I guess I need to think about changing the "native" part of this library 🤔. 
Maybe I can change it from `C++` implementation to `Go` or `rust` - a much simpler API and possibly less error-prone.

**Comment by gonuit** [comment]
Hi @Skycoder42,
Since we do not want to "communicate" with a native process acting as a bridge, instead we want the process to directly use the shell to have a native feel. For example, with this, it can render and delete lines, wait for key inputs and so on

**Comment by gonuit** [comment]
I was experimenting with the [ProcessStartMode.inheritStdio](https://api.dart.dev/stable/3.1.5/dart-io/ProcessStartMode/inheritStdio-constant.html) before, But it did not work as expected, but I can't recall the problem. I think it's worth going back and testing it again. 

Also, if you have a good idea of what it might look like, feel free to open a PR.

Thank you for your insight! 🚀

**Comment by gonuit** [comment]
Currently supported platforms are:

| Platform |  x64  | Arm64 |
| :------- | :---: | :---: |
| Linux    |   ✅   |   ✅   |
| Windows  |   ✅   |   ❌   |
| MacOs    |   ✅   |   ✅   |

If the error still occurs, please reopen this issue.
