### ISSUE TITLE
Not working with Dart 3+

### ISSUE THREAD

**Issue by g0dzillaa** [gonuit/rps#8]
Getting `rps as globally activated doesn't support Dart 3.0.0-312.0.dev, try: dart pub global activate rps`

**Comment by g0dzillaa** [comment]
Please see #9

**Comment by gonuit** [comment]
Merged 💪🏻. Thank you for your PR.
You can now test [the latest preview version of the package](https://pub.dev/packages/rps/versions/0.7.0-dev.1) 🚀 .
